# Generated by Django 2.0.2 on 2018-10-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sn',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='学号'),
        ),
    ]
