# Generated by Django 2.0.2 on 2018-10-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181023_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='num',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
