# Generated by Django 2.0.2 on 2018-10-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_stock'),
        ('users', '0003_borrow_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrow',
            unique_together={('user', 'books')},
        ),
    ]
